apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apps.mysql.bleuelab.ca
spec:
  scope: Namespaced
  group: mysql.bleuelab.ca
  names:
    kind: App
    plural: apps
    singular: app
    shortNames: []
    categories:
    - all
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              instance:
                type: string
            required:
            - instance
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
    additionalPrinterColumns:
    - name: Success
      type: boolean
      description: Last operation sucess
      jsonPath: '.status.lastOperationSuccess'
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: instances.mysql.bleuelab.ca
spec:
  scope: Cluster
  group: mysql.bleuelab.ca
  names:
    kind: Instance
    plural: instances
    singular: instance
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              host:
                type: string
              port:
                type: integer
                default: 3306
              ssl:
                type: boolean
                default: true
              user:
                type: string
              pwd:
                type: object
                properties:
                  hashicorpVault:
                    type: object
                    properties:
                      addr:
                        type: string
                      auth:
                        type: string
                      field:
                        type: string
                      mount:
                        type: string
                      path:
                        type: string
                      role:
                        type: string
                    required:
                    - addr
                    - role
                    - auth
                    - path
                    - mount
                    - field
                required:
                - hashicorpVault
            required:
            - host
            - user
            - pwd
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
